//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLibrary_WCFService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookDataContract", Namespace="http://schemas.datacontract.org/2004/07/BookLibrary_WCFService")]
    public partial class BookDataContract : object
    {
        
        private int IdField;
        
        private bool IsAvailableField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable
        {
            get
            {
                return this.IsAvailableField;
            }
            set
            {
                this.IsAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/BookLibrary_WCFService")]
    public partial class BookFault : object
    {
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveBookResult", Namespace="http://schemas.datacontract.org/2004/07/BookLibrary_WCFService")]
    public partial class SaveBookResult : object
    {
        
        private bool IsCompletedField;
        
        private int NewIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCompleted
        {
            get
            {
                return this.IsCompletedField;
            }
            set
            {
                this.IsCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewId
        {
            get
            {
                return this.NewIdField;
            }
            set
            {
                this.NewIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteBookResult", Namespace="http://schemas.datacontract.org/2004/07/BookLibrary_WCFService")]
    public partial class DeleteBookResult : object
    {
        
        private int DeletedIdField;
        
        private string DeletedTitleField;
        
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeletedId
        {
            get
            {
                return this.DeletedIdField;
            }
            set
            {
                this.DeletedIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeletedTitle
        {
            get
            {
                return this.DeletedTitleField;
            }
            set
            {
                this.DeletedTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILibraryService")]
public interface ILibraryService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetBookById", ReplyAction="http://tempuri.org/ILibraryService/GetBookByIdResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(BookLibrary_WCFService.BookFault), Action="http://tempuri.org/ILibraryService/GetBookByIdBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/BookLibrary_WCFService")]
    System.Threading.Tasks.Task<BookLibrary_WCFService.BookDataContract> GetBookByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/AddBook", ReplyAction="http://tempuri.org/ILibraryService/AddBookResponse")]
    System.Threading.Tasks.Task<BookLibrary_WCFService.SaveBookResult> AddBookAsync(BookLibrary_WCFService.BookDataContract book);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/RemoveBook", ReplyAction="http://tempuri.org/ILibraryService/RemoveBookResponse")]
    System.Threading.Tasks.Task<BookLibrary_WCFService.DeleteBookResult> RemoveBookAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/UpdateBook", ReplyAction="http://tempuri.org/ILibraryService/UpdateBookResponse")]
    System.Threading.Tasks.Task<bool> UpdateBookAsync(BookLibrary_WCFService.BookDataContract book);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public interface ILibraryServiceChannel : ILibraryService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public partial class LibraryServiceClient : System.ServiceModel.ClientBase<ILibraryService>, ILibraryService
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public LibraryServiceClient() : 
            base(LibraryServiceClient.GetDefaultBinding(), LibraryServiceClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ILibraryService.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public LibraryServiceClient(EndpointConfiguration endpointConfiguration) : 
            base(LibraryServiceClient.GetBindingForEndpoint(endpointConfiguration), LibraryServiceClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public LibraryServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(LibraryServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public LibraryServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(LibraryServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public LibraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<BookLibrary_WCFService.BookDataContract> GetBookByIdAsync(int id)
    {
        return base.Channel.GetBookByIdAsync(id);
    }
    
    public System.Threading.Tasks.Task<BookLibrary_WCFService.SaveBookResult> AddBookAsync(BookLibrary_WCFService.BookDataContract book)
    {
        return base.Channel.AddBookAsync(book);
    }
    
    public System.Threading.Tasks.Task<BookLibrary_WCFService.DeleteBookResult> RemoveBookAsync(int id)
    {
        return base.Channel.RemoveBookAsync(id);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateBookAsync(BookLibrary_WCFService.BookDataContract book)
    {
        return base.Channel.UpdateBookAsync(book);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    #if !NET6_0_OR_GREATER
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    #endif
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILibraryService))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILibraryService))
        {
            return new System.ServiceModel.EndpointAddress("http://localhost:5150/Services/LibraryService.svc");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return LibraryServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILibraryService);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return LibraryServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILibraryService);
    }
    
    public enum EndpointConfiguration
    {
        
        BasicHttpBinding_ILibraryService,
    }
}
